### ISSUE TITLE
Use EncodeUri() if part of the URL path or EncodeUriComponent() if used as a URL parameter

### ISSUE THREAD

**Issue by semisight** [EdinCuturic/awin-advertiser-mastertag-google-tag-manager#1]
When reviewing your template we've noticed that it is using parameters to build a url. It's a best practice to use [[EncodeUri()](https://developers.google.com/tag-manager/templates/api#encodeuri)](https://developers.google.com/tag-manager/templates/api#encodeuri) if part of the URL path or [[EncodeUriComponent()](https://developers.google.com/tag-manager/templates/api#encodeuricomponent)](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) if used as a URL parameter.

**Comment by EdinCuturic** [comment]
I added the encodeUri https://github.com/EdinCuturic/awin-advertiser-mastertag-google-tag-manager/commit/ec5b664e257567896e1af512a8d4405489152821
